/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardMarketingRouteImport } from './routes/dashboard/marketing'
import { Route as DashboardLotesRouteImport } from './routes/dashboard/lotes'
import { Route as DashboardFerramentasRouteImport } from './routes/dashboard/ferramentas'
import { Route as DashboardDocumentosRouteImport } from './routes/dashboard/documentos'
import { Route as DashboardCrmRouteImport } from './routes/dashboard/crm'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard/configuracoes'
import { Route as DashboardClientesRouteImport } from './routes/dashboard/clientes'
import { Route as DashboardAgendaRouteImport } from './routes/dashboard/agenda'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMarketingRoute = DashboardMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLotesRoute = DashboardLotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFerramentasRoute = DashboardFerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDocumentosRoute = DashboardDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCrmRoute = DashboardCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClientesRoute = DashboardClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/documentos': typeof DashboardDocumentosRoute
  '/dashboard/ferramentas': typeof DashboardFerramentasRoute
  '/dashboard/lotes': typeof DashboardLotesRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/documentos': typeof DashboardDocumentosRoute
  '/dashboard/ferramentas': typeof DashboardFerramentasRoute
  '/dashboard/lotes': typeof DashboardLotesRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/documentos': typeof DashboardDocumentosRoute
  '/dashboard/ferramentas': typeof DashboardFerramentasRoute
  '/dashboard/lotes': typeof DashboardLotesRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/agenda'
    | '/dashboard/clientes'
    | '/dashboard/configuracoes'
    | '/dashboard/crm'
    | '/dashboard/documentos'
    | '/dashboard/ferramentas'
    | '/dashboard/lotes'
    | '/dashboard/marketing'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/agenda'
    | '/dashboard/clientes'
    | '/dashboard/configuracoes'
    | '/dashboard/crm'
    | '/dashboard/documentos'
    | '/dashboard/ferramentas'
    | '/dashboard/lotes'
    | '/dashboard/marketing'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/agenda'
    | '/dashboard/clientes'
    | '/dashboard/configuracoes'
    | '/dashboard/crm'
    | '/dashboard/documentos'
    | '/dashboard/ferramentas'
    | '/dashboard/lotes'
    | '/dashboard/marketing'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/marketing': {
      id: '/dashboard/marketing'
      path: '/marketing'
      fullPath: '/dashboard/marketing'
      preLoaderRoute: typeof DashboardMarketingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/lotes': {
      id: '/dashboard/lotes'
      path: '/lotes'
      fullPath: '/dashboard/lotes'
      preLoaderRoute: typeof DashboardLotesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ferramentas': {
      id: '/dashboard/ferramentas'
      path: '/ferramentas'
      fullPath: '/dashboard/ferramentas'
      preLoaderRoute: typeof DashboardFerramentasRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/documentos': {
      id: '/dashboard/documentos'
      path: '/documentos'
      fullPath: '/dashboard/documentos'
      preLoaderRoute: typeof DashboardDocumentosRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/crm': {
      id: '/dashboard/crm'
      path: '/crm'
      fullPath: '/dashboard/crm'
      preLoaderRoute: typeof DashboardCrmRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/clientes': {
      id: '/dashboard/clientes'
      path: '/clientes'
      fullPath: '/dashboard/clientes'
      preLoaderRoute: typeof DashboardClientesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/agenda': {
      id: '/dashboard/agenda'
      path: '/agenda'
      fullPath: '/dashboard/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardClientesRoute: typeof DashboardClientesRoute
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardCrmRoute: typeof DashboardCrmRoute
  DashboardDocumentosRoute: typeof DashboardDocumentosRoute
  DashboardFerramentasRoute: typeof DashboardFerramentasRoute
  DashboardLotesRoute: typeof DashboardLotesRoute
  DashboardMarketingRoute: typeof DashboardMarketingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardClientesRoute: DashboardClientesRoute,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardCrmRoute: DashboardCrmRoute,
  DashboardDocumentosRoute: DashboardDocumentosRoute,
  DashboardFerramentasRoute: DashboardFerramentasRoute,
  DashboardLotesRoute: DashboardLotesRoute,
  DashboardMarketingRoute: DashboardMarketingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
